# Generated by Django 4.1.4 on 2023-01-06 01:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('strona', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ogloszenie',
            name='data_utworzenia',
        ),
        migrations.CreateModel(
            name='Użytkownik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
