# Generated by Django 4.1.4 on 2023-01-06 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strona', '0002_remove_ogloszenie_data_utworzenia_użytkownik'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='użytkownik',
            name='user',
        ),
        migrations.AddField(
            model_name='użytkownik',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
