# Generated by Django 4.1.4 on 2023-01-06 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strona', '0003_remove_użytkownik_user_użytkownik_profile_pic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Użytkownik',
        ),
    ]
