# Generated by Django 4.1.4 on 2023-01-08 03:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('strona', '0004_delete_użytkownik'),
    ]

    operations = [
        migrations.AddField(
            model_name='ogloszenie',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ogloszenie',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
