# Generated by Django 4.1.4 on 2023-01-10 18:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('strona', '0008_alter_userprofile_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='tokens',
            field=models.ManyToManyField(blank=True, related_name='tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='pfp',
            field=models.ImageField(blank=True, default='static/images/twojekonto-ikona_czarna.png', upload_to='static/images/profile_pictures'),
        ),
    ]
