# Generated by Django 4.1.4 on 2023-01-10 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strona', '0009_userprofile_tokens_alter_userprofile_pfp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='tokens',
        ),
    ]
