# Generated by Django 4.1.4 on 2023-01-10 23:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('strona', '0011_remove_userprofile_friends_delete_friend'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='tokens',
            field=models.ManyToManyField(blank=True, related_name='tokens', to=settings.AUTH_USER_MODEL),
        ),
    ]
