# Generated by Django 4.1.4 on 2023-01-11 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strona', '0014_userprofile_tokens_nauczajogloszenie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nauczajogloszenie',
            old_name='zakres',
            new_name='zakres_do',
        ),
        migrations.AddField(
            model_name='nauczajogloszenie',
            name='zakres_od',
            field=models.CharField(choices=[('6 podstawówka', '6 podstawówka'), ('7 podstawówka', '7 podstawówka'), ('8 podstawówka', '8 podstawówka'), ('1 liceum', '1 liceum'), ('2 liceum', '2 liceum'), ('3 liceum', '3 liceum'), ('4 liceum', '4 liceum')], max_length=20, null=True),
        ),
    ]
