# Generated by Django 4.1.4 on 2023-01-11 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strona', '0015_rename_zakres_nauczajogloszenie_zakres_do_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ogloszenie',
            old_name='zakres',
            new_name='zakres_materialu',
        ),
    ]
