# Generated by Django 4.1.4 on 2023-01-11 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strona', '0016_rename_zakres_ogloszenie_zakres_materialu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='tokens',
        ),
    ]
