# Generated by Django 4.1.4 on 2023-01-12 21:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strona', '0017_remove_userprofile_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='tokens',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
