# Generated by Django 4.1.4 on 2023-01-15 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strona', '0021_messagemodel_threadmodel_delete_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='threadmodel',
            name='has_unread',
            field=models.BooleanField(default=False),
        ),
    ]
