# Generated by Django 4.1.4 on 2023-01-16 04:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strona', '0023_remove_userprofile_pfp_remove_userprofile_tokens_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='tokens',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
